name: Docker Builds

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
      - name: GetTag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker build
        run: |
          docker build . -f ./envs/Dockerfile -t latest -t webatlas-pipeline:${{ steps.previoustag.outputs.tag }}
          docker build . -f ./envs/build_config/Dockerfile -t latest -t webatlas-pipeline-build-config:${{ steps.previoustag.outputs.tag }}

      - name: docker push
        run: |
          docker push webatlas-pipeline:${{ steps.previoustag.outputs.tag }}
          docker push webatlas-pipeline:latest
          docker push webatlas-pipeline-build-config:${{ steps.previoustag.outputs.tag }}
          docker push webatlas-pipeline-build-config:latest
